### ISSUE TITLE
Separate out moksha deps

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg#121]
Not everyone wants the fedmsg-hub mechanics (and the deps!) by default.

People who just want to listen for messages should be able to with fedmsg.tail_messages without pulling in all of twisted.

Kind of like http://www.fedmsg.com/en/latest/consuming/#diy-listening-with-raw-zeromq

**Comment by yazman** [comment]
I'm closing this issue (at long last!) as the above mentioned pull request resolves it.
