### ISSUE TITLE
Add fedmsg-meta-debian to the topics docs

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg#159]
It would be cool to publicly list the debian endpoints and message types in the docs the way we do with fedora messages.  Probably on their own page?

**Comment by jogenderkota** [comment]
@ralphbean I wish to work on this bug. Does the doc still need work?

**Comment by jeremycline** [comment]
Since the fedmsg docs no longer list the endpoints ([fedmsg_meta](https://fedora-fedmsg.readthedocs.io/en/latest/) docs generate them, I believe), I'm going to close this ticket.
