### ISSUE TITLE
Add fedmsg messages to mirrormanager

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg#245]
might be nice to have mirror added / mirror removed

**Comment by Devyani-Divs** [comment]
@ralphbean @pypingou , hello, can you please tell me how can i test my changes in mirrormanager2. Thankyou :)

**Comment by Aayush-Kasurde** [comment]
It seems that this issue is fixed using [PR#16](https://github.com/fedora-infra/mirrormanager2/pull/16). Can some close this issue please?

**Comment by ralphbean** [comment]
Yes.  Thanks!
