### ISSUE TITLE
BadObject when deleting a branch from git repository

### ISSUE THREAD

**Issue by robyduck** [fedora-infra/fedmsg#320]
I see this error every time I'm going to delete a branch from the git repository (in my case fedora-web git repo). When I push this to the remote server I get a BadObject error, I'm on another branch when deleting and all branches are up to date. Here is a traceback:

``` python
git push origin --delete zanata-f22-alpha           
remote: Traceback (most recent call last):
remote:   File "./hooks/post-receive-chained.d/post-receive-fedmsg", line 47, in <module>
remote:     commits = map(_build_commit, lines)
remote:   File "./hooks/post-receive-chained.d/post-receive-fedmsg", line 31, in _build_commit
remote:     name=commit.author.name,
remote:   File "/usr/lib64/python2.6/site-packages/gitdb/util.py", line 238, in __getattr__
remote:     self._set_cache_(attr)
remote:   File "/usr/lib/python2.6/site-packages/git/objects/commit.py", line 132, in _set_cache_
remote:     binsha, typename, self.size, stream = self.repo.odb.stream(self.binsha)
remote:   File "/usr/lib64/python2.6/site-packages/gitdb/db/base.py", line 259, in stream
remote:     return self._db_query(sha).stream(sha)
remote:   File "/usr/lib64/python2.6/site-packages/gitdb/db/base.py", line 243, in _db_query
remote:     raise BadObject(sha)
remote: gitdb.exc.BadObject: BadObject: 0000000000000000000000000000000000000000
Killed by signal 1.
To ssh://git.fedorahosted.org/git/fedora-web.git
 - [deleted]         zanata-f22-alpha
```

Thanks.

**Comment by ralphbean** [comment]
Sorry @robyduck.  Long story:  that git library used by that hook (and the dist-git hook) is awful.  It fails on deleting branches *and* on pushing tags *and* on pushing gpg-signed commits.

We *just* rewrote the dist-git hook to use pygit2 which can handle all of those scenarios.  It's on my list to port the fedorahosted hook to work the same way.  Hopefully soon.

**Comment by jeremycline** [comment]
I'm pretty certain this issue is no longer relevant, but please re-open it if you feel it's still an issue with fedmsg today.
