### ISSUE TITLE
fedmsg-relay unnecessary dependency

### ISSUE THREAD

**Issue by wcott** [fedora-infra/fedmsg#330]
fedmsg-relay has a dependency on moksha (found in this src rpm: http://koji.fedoraproject.org/koji/packageinfo?packageID=9437) that is not necessary to the functionality of fedmsg-relay.

**Comment by ralphbean** [comment]
As I look more closely, I'm not sure that this is true.

Here's the requirement on python-moksha-hub http://pkgs.fedoraproject.org/cgit/fedmsg.git/tree/fedmsg.spec#n31 .. but that is not the same as a requirement on that meta moksha package.

Can you clarify where you're seeing this?

**Comment by wcott** [comment]
This is not an issue, moksha is not a requirement of fedmsg-relay.

**Comment by ralphbean** [comment]
Looks like this is all good.

**Comment by ralphbean** [comment]
Thanks @wcott!
