### ISSUE TITLE
`tail_messages()` yields message topics as bytestrings not strings in Python 3

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/fedmsg#362]
Viz:

    [adamw@adam relval (master *%)]$ python3 ./consumer.py test
    DEBUG:__main__:b'org.fedoraproject.prod.buildsys.task.state.change'
    DEBUG:__main__:b'org.fedoraproject.dev.pungi.compose.status.change'
    DEBUG:__main__:b'org.fedoraproject.prod.buildsys.build.state.change'
    ^CInterrupted, exiting...
    [adamw@adam relval (master *%)]$ python2 ./consumer.py test
    DEBUG:__main__:org.fedoraproject.prod.pungi.compose.phase.stop
    DEBUG:__main__:org.fedoraproject.prod.pungi.compose.phase.start
    ^CInterrupted, exiting...

I just debug logged the `topic` value - the third item in the tuples yielded from `tail_messages()`. Sorry, I'm just too tired to figure this one out and send a patch. We can work on it tomorrow.

**Comment by ralphbean** [comment]
That makes sense.  zeromq almost certainly hands us bytes and it is arguably fedmsg's duty to convert that to unicode strings.
