### ISSUE TITLE
'FedMsgContext' object has no attribute 'publisher'

### ISSUE THREAD

**Issue by dubuqingyun** [fedora-infra/fedmsg#378]
fedmsg: no matter in console or python file, every time I call the fedmsg.publish, an error always occurs with " 'FedMsgContext' object has no atribute 'publisher' ", I have checked the file core.py and 'FedMsgContext' object, it does have that atrribute.
So, I wonder how this happened and how to fix it.
I get  fedmsg by run the command: sudo yum install fedmsg fedmsg-hub.
thanks.

**Comment by pypingou** [comment]
This got close, does it mean you found the fix?
