### ISSUE TITLE
Repo description still says "Fedora Messaging"

### ISSUE THREAD

**Issue by ncoghlan** [fedora-infra/fedmsg#383]
The repo description should be updated to say "Federated Message Bus" to align with the changes made to fedmsg.org

**Comment by sayanchowdhury** [comment]
I have updated the repo description but we should update the README too.

How does this sound?
fedmsg -- Federated Message Bus

fedmsg (FEDerated MeSsaGe bus) is a python package and API defining a brokerless messaging architecture to send and receive messages to and from applications. Please see doc here or fedmsg online doc for more info.

**Comment by ncoghlan** [comment]
Those updates look good to me. It's likely also worth explicitly mentioning:

    The command line applications `fedmsg-logger` and `fedmsg-tail` allow messages to be sent and received in a language independent way.

**Comment by jeremycline** [comment]
It looks like this has been resolved.
