### ISSUE TITLE
Development section on documentation needs update

### ISSUE THREAD

**Issue by tvieira** [fedora-infra/fedmsg#384]
When building fedmsg from scratch following the Development section in the documentation I get two errors:

1. missing libffi-devel from the 'Development Dependencies' as cryptography python library depends on it.

```
 c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.


```
2. python-m2crypto is not a Fedora package anymore, and it should be replaced by m2crypto and swig.

```
 running build_ext
  building 'm2ext._m2ext' extension
  swigging swig/m2ext.i to swig/m2ext_wrap.c
  swig -python -I/usr/include/python2.7 -I/usr/include -includeall -noproxy -o swig/m2ext_wrap.c swig/m2ext.i
  unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1
```

**Comment by tvieira** [comment]
Just did a push with the changes on #385

**Comment by jeremycline** [comment]
I'm going to close this since it's been merged
