### ISSUE TITLE
fedmsg-0.18.3: tests fail in crypto

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fedmsg#411]
Trying to build fedmsg in rawhide fails in tests. 

```
Does fedmsg.config._recursive_update produce the expected result? ... ok
test_send_message (fedmsg.tests.test_core.TestCore)
send_message is deprecated ... ok
test_invalid_validator (fedmsg.tests.test_crypto_switching.TestCryptoSwitching)
Try to verify an x509 message when only gpg is allowed. ... ok
test_failed_validation (fedmsg.tests.test_crypto_x509.TestCryptoX509)
Try to fail validation. ... /var/tmp/rpm-tmp.FX8uYf: line 31: 10522 Segmentation fault      (core dumped) PYTHONPATH=$(pwd) python setup.py test
RPM build errors:
```

dmesg on the builder has: 

[Sat May 27 18:32:29 2017] python[10522]: segfault at 49 ip 00000000f6e09585 sp 00000000ffd29d00 error 4 in libcrypto.so.1.1.0e[f6c85000+22f000]

Perhaps we should move to x509_ng which doesn't use mcrypto, but python-crypto

**Comment by jeremycline** [comment]
I would definitely be in favor of dropping M2Crypto. The feature we need for us to do so was added to cryptography in [1.6](https://cryptography.io/en/latest/changelog/#id8) (support for signing and verifying RSA, DSA, and ECDSA signatures). It looks like RHEL ships 1.3.1.

Personally, I'm fine with upstream requiring 1.6 and having us build 1.6 for EL7, but I think other people should probably weigh in. @ralphbean, @pypingou, @puiterwijk any thoughts, objections, etc?

**Comment by puiterwijk** [comment]
I would be much in favor of moving to Cryptography and making that the primary/only supported crypto module for x509 (aka, make x509-ng replace x509).
I just think that we need to very carefully test the entire stack on both EL7 and F25 :).

**Comment by pypingou** [comment]
python-cryptography isn't in epel7, it's in RHEL proper so getting it updated to 1.6 is not a trivial task

**Comment by puiterwijk** [comment]
Let's see what version lands in RHEL7.4. Worst case we can always try to build it in the Infra tag.

**Comment by jeremycline** [comment]
We also need pyOpenSSL >= 0.15 to verify a certificate has been signed by our CA. If we want it to also handle CRL for us, that requires 16.1.0. I'm still in favor of switching and (as @puiterwijk said), building it in the infra tag.

**Comment by jeremycline** [comment]
The required version of cryptography and pyOpenSSL are available in Fedora 26+. The M2Crypto implementation is still available for older platforms.
