### ISSUE TITLE
Proposal: fedmsg-0.19 is the last release that supports Python 2.6

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fedmsg#418]
I would like to propose that we drop support for Python 2.6 after the next release of fedmsg.

**Comment by pypingou** [comment]
hm, we still have some EL6 boxes that are running fedmsg iirc (FAS comes to mind as an example)

**Comment by pypingou** [comment]
And there may be other customer using fedmsg on old boxes

**Comment by jeremycline** [comment]
I'm not opposed to backporting critical bugfixes to 0.19, but plenty of our dependencies have already dropped 2.6 (Twisted, for example).

**Comment by jeremycline** [comment]
Fixed in #469
