### ISSUE TITLE
Use the module name as the logger name

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fedmsg#441]
We should change all fedmsg logging to occur from a logger acquired using ``logging.getLogger(__name__)`` (the recommended practice in the Python [logging documentation](https://docs.python.org/2/library/logging.html#logger-objects)).

There's loggers using the package name ("fedmsg"), a package name outside of fedmsg ("moksha"), and logging instances are being passed around/stored on objects. This makes it much more annoying to track down where logs are being emitted, and also makes configuration unnecessarily difficult.

**Comment by cha-ku** [comment]
Hi @jeremycline , I would like to work on this issue. Could you please assign this to me?

**Comment by jeremycline** [comment]
I don't think I can assign it to you since you're not part of the fedora-infra GitHub organization. I think commenting here is enough to let people know you're working on it.

**Comment by cha-ku** [comment]
Alright then. Will work on this. Thanks! :)

**Comment by jeremycline** [comment]
Fixed in #479
