### ISSUE TITLE
remove duplicate message topics 

### ISSUE THREAD

**Issue by matt8754** [fedora-infra/fedmsg#457]
Just notice that there are two duplicate message topics in the docs.

https://fedora-fedmsg.readthedocs.io/en/latest/topics.html#taskotron-result-new

https://fedora-fedmsg.readthedocs.io/en/latest/topics.html#trac-git-receive

**Comment by matt8754** [comment]
Actually, there are more. It might be a bug when the doc was built.

**Comment by jeremycline** [comment]
Hey @matt8754, thanks for the report.

Those docs aren't built from fedmsg sources, so I've moved the issue to fedmsg_meta_fedora_infrastructure.
