### ISSUE TITLE
failed to install python2-fedmsg on f27

### ISSUE THREAD

**Issue by matt8754** [fedora-infra/fedmsg#487]
My f27 koji build failed with:

DEBUG util.py:439:  Last metadata expiration check: 0:00:00 ago on Tue 24 Oct 2017 01:33:55 AM UTC.
DEBUG util.py:439:  Error: 
DEBUG util.py:439:   Problem: package python2-fedmsg-1.0.1-4.fc27.noarch requires python-moksha-hub >= 1.3.2, but none of the providers can be installed
DEBUG util.py:439:    - package python-moksha-hub-1.5.3-4.fc27.noarch requires python2-twisted, but none of the providers can be installed
DEBUG util.py:439:    - package fedmsg-1.0.1-4.fc27.noarch requires python2-fedmsg = 1.0.1-4.fc27, but none of the providers can be installed
DEBUG util.py:439:    - package python2-twisted-16.4.1-5.fc27.x86_64 requires python-crypto, but none of the providers can be installed
DEBUG util.py:439:    - conflicting requests
DEBUG util.py:439:    - nothing provides libtomcrypt.so.0()(64bit) needed by python2-crypto-2.6.1-17.fc27.x86_64

More logs can be found here:

https://kojipkgs.fedoraproject.org//work/tasks/7777/22657777/root.log

This currently blocks me to create a package update for f27 and please fix it asap, thanks.

**Comment by ralphbean** [comment]
Looks like something's broken in the f27 buildroot :(

**Comment by bowlofeggs** [comment]
I reported this against libtomcrypt:

https://bugzilla.redhat.com/show_bug.cgi?id=1505641

**Comment by scaronni** [comment]
I've triggered a rebuild and an update of libtomcrypt yesterday, but this seems unrelated. The current libtomcrypt package is still in the repository:

https://koji.fedoraproject.org/koji/buildinfo?buildID=928909

It seems the buildroot is getting the wrong packages. By pulling the udpates that I just pushed I can't reproduce the problem:

https://bodhi.fedoraproject.org/updates/FEDORA-2017-53fedf1c92

```
$ sudo rpm -Uvh \
  https://kojipkgs.fedoraproject.org//packages/libtomcrypt/1.18.0/1.fc27/x86_64/libtomcrypt-1.18.0-1.fc27.x86_64.rpm \
  https://kojipkgs.fedoraproject.org//packages/python-crypto/2.6.1/19.fc27/x86_64/python2-crypto-2.6.1-19.fc27.x86_64.rpm```

**Comment by jeremycline** [comment]
Hey @matt8754, thanks for the report.

Since this is a packaging issue outside of fedmsg's control, I think it's best to track this issue with the bugzilla @bowlofeggs opened.
