### ISSUE TITLE
supporting other programming languages for consumers than Python

### ISSUE THREAD

**Issue by glensc** [fedora-infra/fedmsg#503]
Would be useful if could write consumers in other languages than Python.

**Comment by pypingou** [comment]
There is already a java one, but after all fedmsg is just a wrapper around 0mq so there should be other languages supported for it

**Comment by jeremycline** [comment]
[These are the official language bindings for ZeroMQ](http://zeromq.org/bindings:_start). There's also some unofficial bindings for more exotic languages.

**Comment by glensc** [comment]
found [fedmsg-rabbitmq-serializer](https://pagure.io/fedmsg-rabbitmq-serializer), might be easier to use rabbitmq for reading events. not sure is it bidirectional to also emit events.
