### ISSUE TITLE
documentation: path for configuration

### ISSUE THREAD

**Issue by glensc** [fedora-infra/fedmsg#505]
the [configuration](https://fedmsg.readthedocs.io/en/stable/configuration/) documentation explains config details, but not a word where to create the configs.

i know  top of my head `/etc/fedmsg.d` is used for system config, but what is the user path? guessed xdg compatible `~/.config/fedmsg.d` path did not work. 

```
$ fedmsg-tail --pretty
Traceback (most recent call last):
  File "/usr/local/bin/fedmsg-tail", line 11, in <module>
    sys.exit(tail())
  File "/usr/local/lib/python2.7/site-packages/fedmsg/commands/tail.py", line 210, in tail
    command = TailCommand()
  File "/usr/local/lib/python2.7/site-packages/fedmsg/commands/__init__.py", line 41, in __init__
    self.config = self.get_config()
  File "/usr/local/lib/python2.7/site-packages/fedmsg/commands/__init__.py", line 49, in get_config
    fedmsg_command=True,
  File "/usr/local/lib/python2.7/site-packages/fedmsg/config.py", line 609, in load_config
    raise ValueError("No config value 'endpoints' found.")
ValueError: No config value 'endpoints' found.
```

**Comment by pypingou** [comment]
IIRC, it loads from ``/etc/fedmsg.d`` indeed as well as the current working directory. I don't think ``~/.config/`` is supported.

**Comment by jeremycline** [comment]
It looks like it got documented in the [config module](https://github.com/fedora-infra/fedmsg/blob/develop/fedmsg/config.py#L26-L30), but it's not being rendered in the Sphinx docs. It'd probably be good to pull the configuration value details into the config module and render the whole thing.

**Comment by glensc** [comment]
indeed, seems `~/.fedmsg.d` is loaded from "user directory".

ps: never link to a branch.
hint: use `y` hotkey in github to create permalink
ps2: edit your post to have permalink there ;)
