### ISSUE TITLE
RFE: Document how config files in /etc/fedmsg.d get loaded

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/fedmsg#511]
It would be nice if http://www.fedmsg.com/en/stable/configuration/ had some notes about the files in ```/etc/fedmsg.d/```, and in particular documented how they get parsed and turned into a single config. I gather than there is some mechanism that can merge dictionaries together in some fashion, and that configs might be loaded in lexigraphic order, but it'd be nice to have it in writing.

**Comment by glensc** [comment]
related: https://github.com/fedora-infra/fedmsg/issues/505
