### ISSUE TITLE
CNAME issue with www.fedmsg.com

### ISSUE THREAD

**Issue by davidfischer** [fedora-infra/fedmsg#518]
I work on Read the Docs and we made a DNS change which broke `www.fedmsg.com`. We fixed it for you by adding a DNS record specific for fedmsg but you have a particularly unique (read: unsupported) setup that I wanted you to be aware of. You are CNAMEing `www.fedmsg.com` to `fedmsg.rtfd.org`. Instead, please CNAME to `readthedocs.io`.

    $ dig www.fedmsg.com CNAME +short           # fedmsg.rtfd.org.

rtfd.org is a domain that we simply redirect to readthedocs.io. It wasn't intended for people to CNAME projects to. Your previous setup just happened to work because readthedocs.io and rtfd.org resolved to the same host. They don't anymore. Here are our [docs](https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-support) on the subject, but **long story short, please update your CNAME when you get a chance to `readthedocs.io`**

If you change the CNAME, you can:

* get an SSL certificate for the domain (once we remove our DNS record specific for your domain)
* mark the domain as HTTPS so that we will generate HTTPS links for the domain
* within a few weeks we should start ensuring that all domains marked HTTPS upgrade insecure HTTP requests.

**Comment by jeremycline** [comment]
I've filed a ticket with Fedora Infrastructure to fix this: https://pagure.io/fedora-infrastructure/issue/7177

**Comment by puiterwijk** [comment]
@lmacken owns this domain, maybe he can chime in and either update his nameservers or hand the domain over?

**Comment by ralphbean** [comment]
Pinged @lmacken on telegram.

**Comment by lmacken** [comment]
I just updated the CNAME to `readthedocs.io`, and would be happy to transfer this domain to you guys.

Can you give me an email address or namecheap username to change it to? Thanks ;)

**Comment by davidfischer** [comment]
Everything looks good on Read the Docs. Feel free to close this: https://www.fedmsg.com/

**Comment by lmacken** [comment]
I will be letting this domain expire on Oct 9, 2018, so if you wish to keep it please send me transfer details.

**Comment by puiterwijk** [comment]
@lmacken you can transfer it to patrick@puiterwijk.org (namecheap email, username "puiterwijk"), and I'll take care of it from there. Thanks.

**Comment by lmacken** [comment]
Namecheap transfer initiated. Thanks, @puiterwijk!

**Comment by puiterwijk** [comment]
@lmacken Sorry, the namecheap email with the notif got lost. Could you re-initiate it?
